### ISSUE TITLE
Can't inherit from String class and some `fun redefinition with different signature` error (+ Deprecation of the compile argument (is now build))

### ISSUE THREAD

**Issue by Demonstrandum** [phoffer/crystalized_ruby#9]
Some stuff isn't working
when compiling I get this message:
```shell
$> rake compile
compiling native extensions
Deprecation: The compile command was renamed to build and will be removed in a future version.
make: *** [Makefile:25: crystalized_ruby.o] Error 1
```
I see where the issue is and try doing what `crystalized_ruby.o` does in the make file:
```shell
crystal compile --cross-compile --target $(UNAME) $<
# becomes
crystal compile --cross-compile --target  "x86_64-unknown-linux-gnu" crystalized_ruby.cr
```
And see this:
```
Deprecation: The compile command was renamed to build and will be removed in a future version.
Error in crystalized_ruby.cr:1: while requiring "./src/lib_ruby/lib_ruby"

require "./src/lib_ruby/lib_ruby"
^

in src/lib_ruby/lib_ruby.cr:1: Cannot inherit from String

require "../../../src/lib_ruby.cr"
^
```
I try to compile `lib_ruby.cr` from the require ` "../../../src/lib_ruby.cr"`
and get a better error message
```shell
[ ~/Git/crystalized_ruby/ext ] $> crystal compile --cross-compile --target  "x86_64-unknown-linux-gnu" ../src/lib_ruby.cr 
# And get this
Deprecation: The compile command was renamed to build and will be removed in a future version.
Error in /home/stroop/Git/crystalized_ruby/src/lib_ruby.cr:261: Cannot inherit from String

class RubySymbol < String
      ^
```
Looks like inheriting from String isn't allowed, and found this in the crystal-lang source:
https://github.com/crystal-lang/crystal/blob/master/src/string.cr#L142
So, I cloned crystal and removed those lines that disallow inheriting from the String class from string.cr and compiled the modified crystal.
I then tried to do it all over again, but, got these error messages instead:
```shell
[ ~/Git/crystal ] hist: 943, jobs: 0
$>  bin/crystal compile --cross-compile --target  "x86_64-unknown-linux-gnu" ../crystalized_ruby/src/lib_ruby.cr 
Using compiled compiler at `.build/crystal'
Deprecation: The compile command was renamed to build and will be removed in a future version.
Error in ized_ruby/src/lib_ruby.cr:63: fun redefinition with different signature (was `fun rb_define_method(klass : VALUE, name : ::Pointer(UInt8), func : METHOD_FUNC, argc : Int32)` at /home/stroop/Git/crystalized_ruby/src/lib_ruby.cr:56:3)

  fun rb_define_method(klass : LibRuby::VALUE, name : UInt8*, func : METHOD_FUNC, argc : Int32)
  ^


[ ~/Git/crystal ] hist: 944, jobs: 0
$>  bin/crystal compile --cross-compile --target  "x86_64-unknown-linux-gnu" ../crystalized_ruby/ext/crystalized_ruby.cr 
Using compiled compiler at `.build/crystal'
Deprecation: The compile command was renamed to build and will be removed in a future version.
Error in ized_ruby/ext/crystalized_ruby.cr:1: while requiring "./src/lib_ruby/lib_ruby"

require "./src/lib_ruby/lib_ruby"
^

in ized_ruby/ext/src/lib_ruby/lib_ruby.cr:1: while requiring "../../../src/lib_ruby.cr"

require "../../../src/lib_ruby.cr"
^

in ized_ruby/src/lib_ruby.cr:63: fun redefinition with different signature (was `fun rb_define_method(klass : VALUE, name : ::Pointer(UInt8), func : METHOD_FUNC, argc : Int32)` at /home/stroop/Git/crystalized_ruby/src/lib_ruby.cr:56:3)

  fun rb_define_method(klass : LibRuby::VALUE, name : UInt8*, func : METHOD_FUNC, argc : Int32)
  ^
```
I think somethings broken.

**Comment by phoffer** [comment]
There are a few problems caused by changes to Crystal in the last few months. The last issue you encountered was the first one that happened, and is the biggest. 

To handle varying argument counts, I had to hack around the function definitions. That isn't possible anymore, and the only other way to do it is a macro based approach that has been also checked out (see [this gist](https://gist.github.com/spalladino/10c829db3191a89a8ba73bb001d3c921) for more info). 

In the time since I worked on this, the Crystal team has added `DSL for writing Ruby extensions` to their [roadmap](https://github.com/crystal-lang/crystal/wiki/Roadmap).

Because they have become interested in this idea, and updating it would require a substantial amount of work, I have been holding off on fixing, to see what other language changes there might be and also how they would like to approach the problem. 

I'm sorry I can't be of more assistance at the moment. Hopefully work on this concept (whether in this project or as part of Crystal lang) will ramp up again in the next few months.
